src/AndrasTimarTGV/Components/BannerViewComponent.cs
using AndrasTimarTGV.Models;
using AndrasTimarTGV.Models.Entities;
using AndrasTimarTGV.Models.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AndrasTimarTGV.Components
{
    public class BannerViewComponent : ViewComponent
    {
        private readonly UserManager<AppUser> UserManager;
        private readonly IBannerTextService BannerTextService;

        public BannerViewComponent(UserManager<AppUser> userManager, IBannerTextService bannerService)
        {
            UserManager = userManager;
            BannerTextService = bannerService;
        }

        public IViewComponentResult Invoke()
        {
            AppUser user = UserManager.FindByNameAsync(HttpContext.User.Identity.Name ?? "").Result;
            if (user != null)
            {
                return View(BannerTextService.GetBannerTextForLang(user.DefaultLanguage));
            }
            return View(BannerTextService.GetBannerTextForLang(Language.En));
        }
    }
}

src/AndrasTimarTGV/Components/LoginFormViewComponent.cs
using AndrasTimarTGV.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AndrasTimarTGV.Components
{
    public class LoginFormViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View(new LoginUserViewModel());
        }
    }
}

src/AndrasTimarTGV/Components/SearchFormViewComponent.cs
using AndrasTimarTGV.Models.Services;
using AndrasTimarTGV.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AndrasTimarTGV.Components
{
    public class SearchFormViewComponent : ViewComponent
    {
        private readonly ICityService CityService;

        public SearchFormViewComponent(ICityService cityService)
        {
            CityService = cityService;
        }

        public IViewComponentResult Invoke()
        {
            return View(new TripViewModel(CityService.Cities));
        }
    }
}

src/AndrasTimarTGV/Controllers/TripController.cs
using System.Linq;
using AndrasTimarTGV.Models.Services;
using AndrasTimarTGV.Models.ViewModels;
using AndrasTimarTGV.Util.Filters;
using Microsoft.AspNetCore.Mvc;

namespace AndrasTimarTGV.Controllers
{
    public class TripController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly ITripService TripService;

        public TripController(ITripService tripService, ICityService cityService)
        {
            TripService = tripService;
        }

        [HttpPost]
        [ModelStateValidityActionFilter]
        public IActionResult List(TripViewModel tripVm)
        {
            var resulTrips = TripService.GetTripsByCitIdsAndDate(tripVm.FromCityId, tripVm.ToCityId, tripVm.Time);
            return View(resulTrips.OrderBy(x => x.Time.Hour));
        }
    }
}

src/AndrasTimarTGV/Views/Shared/Components/SearchForm/Default.cshtml
@model AndrasTimarTGV.Models.ViewModels.TripViewModel

<div><h4>Search</h4></div>
    <form asp-action="List" asp-controller="Trip" method="post">
        <div class="form-group">
            <label>Departure City</label>          
            <div>
                @Html.DropDownListFor(x => x.FromCityId, Model.Cities, "Choose departure city")
            </div>
        </div>
        <div class="form-group">
            <label>Destination City</label>
            <div>
                @Html.DropDownListFor(x => x.ToCityId, Model.Cities, "Choose destination city")
            </div>
        </div>
        <div class="form-group">
            <div><span asp-validation-for="Time" class="text-danger"></span></div>
            <label asp-for="Time"></label>
            <div><span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <input asp-for="Time" type="date" class="form-control"/>
        </div>
        <div class="left">
            <button class="btn btn-primary" type="submit">Search</button>
        </div>
    </form>